// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrfbrboh3a_IFqS32rIluDDCCgYvVZ9hI',
    appId: '1:654571145428:web:5df0a08dac04af308f9341',
    messagingSenderId: '654571145428',
    projectId: 'fruits-hub-f99d3',
    authDomain: 'fruits-hub-f99d3.firebaseapp.com',
    storageBucket: 'fruits-hub-f99d3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7X4-v3AoQi-0GHrfz8RmhIw0BVSPn4rU',
    appId: '1:654571145428:android:35acf156b79194a78f9341',
    messagingSenderId: '654571145428',
    projectId: 'fruits-hub-f99d3',
    storageBucket: 'fruits-hub-f99d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQdIx6Fkh0kh2Jzls2Eb8jVB_lLAJScU',
    appId: '1:654571145428:ios:3f061ef3529c9f4f8f9341',
    messagingSenderId: '654571145428',
    projectId: 'fruits-hub-f99d3',
    storageBucket: 'fruits-hub-f99d3.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );
}
